version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "${APP_PORT:-8080}:80"
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: mysql:8.0
    volumes:
      - data-volume:/var/lib/mysql
      - ./docker/db:/docker-entrypoint-initdb.d:ro
    ports:
      - "${DB_PORT:-33060}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: "${DB_TZ}"
      DB_USER_NAME: "${DB_USER}"
      DB_PW: "${DB_USER_PASSWORD}"
      DB_HOST: "${DB_HOST}"
      DB_NAME: "${DB_NAME}"

volumes:
  data-volume:
