CREATE USER 'user'@'%' IDENTIFIED BY 'password';
GRANT ALTER, CREATE, DELETE, DROP, INSERT, REFERENCES, SELECT, UPDATE ON qzhub.*  TO 'user'@'%';
FLUSH PRIVILEGES;
CREATE DATABASE IF NOT EXISTS qzhub;
